# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_unitmeasure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='user',
        ),
        migrations.RemoveField(
            model_name='portfolioproduct',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='portfolioproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='PortfolioProduct',
        ),
    ]
