# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_remove_profile_email'),
        ('shop', '0003_auto_20170808_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='porfolios', to='shop.Supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='users.Profile')),
            ],
            options={
                'ordering': ('supplier',),
                'verbose_name': 'portfolio',
                'verbose_name_plural': 'portfolios',
            },
        ),
        migrations.CreateModel(
            name='PortfolioProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='portfolios.Portfolio')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_porfolios', to='shop.Product')),
            ],
        ),
    ]
