# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-22 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20170822_1752'),
        ('shop', '0004_supplier_user'),
        ('portfolios', '0004_auto_20170817_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cust_porfolios', to='users.Customer')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cust_porfolios', to='shop.Supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cust_portfolios', to='users.Profile')),
            ],
            options={
                'verbose_name': 'portfolio',
                'verbose_name_plural': 'portfolios',
                'ordering': ('supplier',),
            },
        ),
        migrations.CreateModel(
            name='CustomerPortfolioProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cust_products', to='portfolios.CustomerPortfolio')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cust_product_porfolios', to='shop.Product')),
                ('um', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cust_protfolio_products', to='shop.UnitMeasure')),
            ],
        ),
    ]
