# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-22 15:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_customerportfolio_customerportfolioproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerportfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cust_portfolios', to=settings.AUTH_USER_MODEL),
        ),
    ]
