# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_item_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pub_date',
            field=models.DateTimeField(default='2017-01-01', verbose_name='date published'),
            preserve_default=False,
        ),
    ]
