# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='Order 1', editable=False, max_length=32),
            preserve_default=False,
        ),
    ]
