# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_type',
            field=models.IntegerField(choices=[(1, 'Piece'), (2, 'Weight'), (3, 'Length'), (4, 'Square meter'), (5, 'Cube meter')], default=1),
        ),
    ]
