# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='users.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesperson',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='salesperson', to='users.Profile'),
            preserve_default=False,
        ),
    ]
