# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170822_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
