# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 04:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20170822_1752'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0004_supplier_user'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=20)),
                ('notes', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_orders', to='users.Customer')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_orders', to='shop.Supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='salesperson',
        ),
        migrations.RemoveField(
            model_name='order',
            name='supplier',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=' ', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='um',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.UnitMeasure'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_order_items', to='orders.Order'),
        ),
        migrations.AddField(
            model_name='supplierorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_order_products', to='shop.Product'),
        ),
        migrations.AddField(
            model_name='supplierorderitem',
            name='um',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_order_products', to='shop.UnitMeasure'),
        ),
    ]
