# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20170925_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierorder',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Placed'), (1, 'In process'), (1, 'In delivery'), (3, 'Delivered'), (4, 'Paid'), (5, 'Closed')], default=0),
        ),
    ]
