# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20170925_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_order_items', to='orders.SupplierOrder'),
        ),
    ]
