# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20170822_1752'),
        ('orders', '0004_remove_order_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.Customer'),
            preserve_default=False,
        ),
    ]
